# spec/.rubocop.yml

inherit_from:
  - ../.rubocop.yml

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
  Exclude:
    - './*_helper.rb'

# describe block
Metrics/BlockLength:
  Enabled: false